language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t joaorsilva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joaorsilva/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Ready"
  bucket_name: "elasticbeanstalk-us-east-2-965749552422"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
